### ISSUE TITLE
Publish this package on pypi?

### ISSUE THREAD

**Issue by yoav-orca** [andreasvc/pyre2#13]
This will be valuable for new users and current ones (Pipenv is slow when installing packages from git).
Thanks

**Comment by andreasvc** [comment]
This is a good idea, but I'm not sure whether it makes a big difference.

For fast installation, wheels should be compiled. However, I don't have time to figure out how to do that. I've looked into it in the past, and it seemed quite involved. Contributions welcome.

**Comment by andreasvc** [comment]
See https://pypi.org/project/pyre2/
