### ISSUE TITLE
new pypi wheels

### ISSUE THREAD

**Issue by sarnold** [andreasvc/pyre2#21]
Thanks for taking the cmake PR (hopefully you're surviving the virus apocalypse in decent shape)

This is mainly to document the testing of releases I made from my fork (using only 0.3.2.postN releases, so the next patch version is still available).  This includes both CI testing across the github CI runners and then install/runtime testing using a new python package that depends on pyre2.  It took a few more workarounds in the wheel building but now they all run correctly on the 3 main OS targets (using only the bundled wheel libs and *no* extra libre2 package installs).  Whew...

Given that ^^ I'd say it's ready for uploading new wheels to pypi (other than some readme cleanup).  I did add a platform section to the readme, but I just noticed I didn't update the existing Installation section.  Basically the upshot is:

* normal usage for linux/mac/windows should be: "use the wheels from pypi, ie, pip install pyre2"
* for development/introspection: "use the install from source" method

**Comment by andreasvc** [comment]
All the wheels are on pypi. It works smoothly!
