### ISSUE TITLE
re2.sub replacements with a match of "(.*)" hangs forever

### ISSUE THREAD

**Issue by MartinHowarthMeta** [andreasvc/pyre2#26]
Python version: 3.6
pyre2 version: 0.3.3

The failing test case is:
```
import re, re2
assert re.sub("(.*)", "\\1;replacement", "original") == "original;replacement"
assert re2.sub("(.*)", "\\1;replacement", "original") == "original;replacement"
```
The first of these (using python's `re`) works. The second (using `re2`) hangs forever.

I think the problem is that https://github.com/andreasvc/pyre2/blob/master/src/pattern.pxi#L537-L562 loops forever if `count` is 0, and the match will match every time you try to replace (for example, the `.*` in the example above). This means we never hit either of the `break` statements.

Additionally, we have a preference for a "force re2" mode which would use re2 behaviour even if we have a backreference. We're migrating from the original facebook pyre2 to this module because its much more actively maintained (thank you!) and available on pypi. Given we're not building a library, we don't need a drop-in replacement for python's `re` and would prefer the (presumably more performant) option of purely using `re2`. That might also be an alternate route to unblock us on this issue.

**Comment by andreasvc** [comment]
Thanks for reporting this!

Actually, Python's re behaves differently than in your assert statement:
```
$ python3 -c 'import re; print(re.sub("(.*)", "\\1;replacement", "original"))'
original;replacement;replacement
```

**Comment by andreasvc** [comment]
Hm, actually: python 3.6 behaves as you wrote, but I was using 3.7. Curious ...

**Comment by rkday** [comment]
Thanks, @andreasvc ! Do you have a timeline for a 0.3.4 release with this fix in?

**Comment by MartinHowarthMeta** [comment]
Thanks for the fix - a new release containing it would be great please!

**Comment by andreasvc** [comment]
@MartinHowarthMeta @rkday new version has been released
