### ISSUE TITLE
c++ 2011 compiler requirement error

### ISSUE THREAD

**Issue by dtyszkajr** [andreasvc/pyre2#4]
Idk if this is the right place for this.

I was getting an error when installing:
```
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
```
Adding '-std=c++11' to the extra_compile_args variable in the setup.py file seems to solve that

**Comment by andreasvc** [comment]
The thing is that this parameter is not supported with CentOS 6, so there should be some way to add it only when needed.

**Comment by andreasvc** [comment]
Which compiler/OS are you using? If you look at setup.py, currently it uses `-std=c++11` when it detects `clang`; this condition could be tweaked.

**Comment by dtyszkajr** [comment]
ubuntu10.04
python3.5.2
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

**Comment by mayk93** [comment]
I had the same error, on `Ubuntu 16.04` with `python3.5`:

`error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.`

My fix was also to add `-std=c++11` to `extra_compile_args `.

For the `CentOS 6` issue you mentioned, using the alternate flag suggested by the error log, ` -std=gnu++11`, would that work?

Alternatively, and perhaps a better solution, using `platform`

```
import platform
platform.platform()
```

This should return enough information of the platform to solve the issue.

I'll make a pull request for this.

**Comment by andreasvc** [comment]
`-std=gnu++11` does not work either on CentOS 6 (gcc 4.4.7).

**Comment by mayk93** [comment]
Yeah, that's annoying. Regardless, I submitted a pull request that uses a list ( along with the `CLANG` check ) to determine weather or not the flag ought to be added or not.
