### ISSUE TITLE
Group-named regex's groupdict() incompatible with native re

### ISSUE THREAD

**Issue by ggballas** [andreasvc/pyre2#6]
This is a fantastic library, just a small issue of incompatibility with the native re library that I found while working with it:

```
import re, re2
pat = b'(?P<A>aaa)|(?P<B>bbb)'
p = re.compile(pat)
p2 = re2.compile(pat)

p.match(b'aaa').groupdict()
>>> {'A': b'aaa', 'B': None}

p2.match(b'aaa').groupdict()
>>> {b'A': b'aaa', b'B': None}
```

In re, the group names are strings even though the pattern was a byte-stream. In re2, the group names are byte-streams.

**Comment by andreasvc** [comment]
Thanks for the report. Let me know if you find further issues.
