### ISSUE TITLE
Missing file: re2/stringpiece.h

### ISSUE THREAD

**Issue by dabacai** [andreasvc/pyre2#7]
Trying to install on Mac OS X 10.9 x86 under Python 3.6.

GCC has been installed using Homebrew.

In virtual env, executing pip3 install https://github.com/andreasvc/pyre2/archive/master.zip, the error occurs during the build of wheel for re2.

  creating build/temp.macosx-10.9-x86_64-3.6/src
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c src/re2.cpp -o build/temp.macosx-10.9-x86_64-3.6/src/re2.o -DPY2=0 -O3 -march=native -DNDEBUG -std=c++11
  src/re2.cpp:446:10: fatal error: 're2/stringpiece.h' file not found
  #include "re2/stringpiece.h"
           ^~~~~~~~~~~~~~~~~~~
  1 error generated.
  error: command 'gcc' failed with exit status 1

**Comment by andreasvc** [comment]
That file should be part of https://github.com/google/re2
Make sure that's installed and can be found by the compiler.

**Comment by dabacai** [comment]
Indeed the compiler couldn't find it. Thank you for looking into this.
