### ISSUE TITLE
mutex file not found 

### ISSUE THREAD

**Issue by goutham-nekkalapu** [andreasvc/pyre2#8]
Hi,

I am facing the following issue, when I try to install it in my environment:

running install
running build
running build_ext
building 're2' extension
/usr/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/name/anaconda/envs/test_123/include -arch x86_64 -I/Users/name/anaconda/envs/test_123/include -arch x86_64 -I/usr/local/include -I/Users/name/anaconda/envs/test_123/include/python3.5m -c src/re2.cpp -o build/temp.macosx-10.6-x86_64-3.5/src/re2.o -DPY2=0 -O3 -march=native -DNDEBUG -std=c++11
In file included from src/re2.cpp:629:
/usr/local/include/re2/re2.h:186:10: fatal error: 'mutex' file not found
#include <mutex>
         ^~~~~~~
1 error generated.
error: command '/usr/bin/clang' failed with exit status 1

I have successfully installed re2 C++ library from : https://github.com/google/re2
my setup:
   Anaconda environment 
   Python : 3.5.5
   Cython : 0.28.3

Any suggestions on how to solve this ? 

thank you,
goutham.

**Comment by andreasvc** [comment]
It seems like it cannot find a file included in Google's re2 library, maybe some include paths are missing? What system are you running? I run Ubuntu/Debian, and installing the package "libre2-dev" takes care of properly installing Google's re2 library.
