### ISSUE TITLE
Compiler flag -march=native could make lib processor dependent

### ISSUE THREAD

**Issue by KSolovyev** [andreasvc/pyre2#9]
This is especially dangerous when you build your app into docker container (or another virtualization type). The lib will be built with the optimisation of CI-server processor and they could be not compatible with the processor of  production machine.

From the gcc docs (http://gcc.gnu.org/onlinedocs/gcc/x86-Options.html):
```
‘native’
This selects the CPU to generate code for at compilation time by determining the processor type of the compiling machine. Using -march=native enables all instruction subsets supported by the local machine (hence the result might not run on different machines). Using -mtune=native produces code optimized for the local machine under the constraints of the selected instruction set.
```

We have encountered this problem and got kernel errors:
```
Sep 17 12:16:44 cryprox-myt-01.aab.yandex.net kernel: traps: python[61336] trap invalid opcode ip:7fa7f2ebfbdb sp:7fff5c14ac20 error:0
Sep 17 12:16:44 cryprox-myt-01.aab.yandex.net kernel:  in re2.so[7fa7f2e87000+43000]
```

Removing flag solved the problem

**Comment by andreasvc** [comment]
I know, it is on purpose. Speed is more important to me than portability. If you know a way to make it optional I will include it, but I want to leave it as the default because speed is the reason to use this module.
